In [0]:
pip install scikit-learn

Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.


In [0]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [0]:
steps = [("Standard_Scaler", StandardScaler()),
         ("Classifier", LogisticRegression())]

In [0]:
steps

[('Standard_Scaler', StandardScaler()), ('Classifier', LogisticRegression())]

In [0]:
pipe=Pipeline(steps)

In [0]:
from sklearn import set_config
set_config(display="diagram")
pipe
Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [0]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000)

In [0]:
X.shape

(1000, 20)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.33,random_state=42)

In [0]:
X_train

array([[-0.81730051, -0.38074883,  0.98515927, ..., -0.48921076,
        -0.02349257, -0.11202731],
       [ 1.25834683, -2.03311726, -0.23686442, ..., -0.4722866 ,
        -1.4613427 , -0.87449414],
       [ 1.53715688,  2.02732115, -0.41317677, ..., -0.24579863,
        -0.67336445,  1.51795823],
       ...,
       [ 0.29766316, -0.80734549,  0.5101648 , ..., -1.96064781,
        -0.4548214 ,  0.52261207],
       [ 1.04901805, -0.79231016, -1.4366164 , ..., -0.22913386,
         0.09734796, -0.15393944],
       [-1.77394033,  1.02845369, -0.64091527, ..., -0.11727271,
        -0.75263582,  0.3823369 ]])

In [0]:
 from sklearn.decomposition import PCA
 from sklearn.svm import SVC

In [0]:
pipe.fit(X_train,y_train)
Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])
y_pred=pipe.predict(X_test)
y_pred

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,

In [0]:
steps=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]
pipe2=Pipeline(steps)
pipe2.fit(X_train,y_train)
Pipeline(steps=[('scaling', StandardScaler()), ('PCA', 
PCA(n_components=3)), ('SVC', SVC())])
pipe2.predict(X_test)

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,

In [0]:
from sklearn.impute import SimpleImputer


In [0]:
 import numpy as np
 numeric_processor=Pipeline(
    
steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy
 ="mean")), ("scaler",StandardScaler())]
 )
numeric_processor
Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [0]:
##categorical procesing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    
steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
          ("onehot",OneHotEncoder(handle_unknown="ignore"))]
 )
categorical_processor
Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', 
strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [0]:
 ## combine processing technqiues
 from sklearn.compose import ColumnTransformer
 categorical_processor = Pipeline(steps=[
    ('imputation_constant', SimpleImputer(fill_value='missing', strategy='constant')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

numeric_processor = Pipeline(steps=[
    ('imputation_mean', SimpleImputer()),
    ('scaler', StandardScaler())
])

preprocessor = ColumnTransformer(
    transformers=[
        ("categorical", categorical_processor, ["gender", "City"]),
        ("numerical", numeric_processor, ["age", "height"])
    ]
)

In [0]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())
pipe
Pipeline(steps=[('columntransformer', ColumnTransformer(transformers=[('categorical', Pipeline(steps=[('imputation_consatnt',SimpleImputer(fill_value='missing',strategy='constant')),('onehot',OneHotEncoder(handle_unknown='ignore'))]),['gender', 'City']),('numerical',
Pipeline(steps=[('imputation_mean',SimpleImputer()),('scaler',StandardScaler())]), ['age', 'height'])])),('logisticregression', LogisticRegression())])

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])